Revert "Merge remote-tracking branch 'origin/develop' into develop"
This reverts commit 98a755a65a3807d6f9d7e9a6d21e92bb5c4f3c03, reversing
changes made to 23b5cab90a55732991c296b43c43ac704b2aad84.

diff --git a/.github/workflows/profiler-build.yml b/.github/workflows/profiler-build.yml
--- a/.github/workflows/profiler-build.yml
+++ b/.github/workflows/profiler-build.yml
@@ -8,22 +8,14 @@ jobs:
   build:
     name: Profiler Build
     runs-on: ubuntu-latest
-    container: ${{ matrix.container }}
+    container: rust:bullseye
     continue-on-error: false
 
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - group: Linux
-            target: x86_64-unknown-linux-gnu
-            build_arg: Unix
-            container: "rust:bullseye"
-          - group: Windows
-            target: x86_64-pc-windows-gnu
-            build_arg: ""
-
     outputs:
+      date: ${{ steps.step1.outputs.date }}
+      clock: ${{ steps.step1.outputs.clock }}
+      tag: ${{ steps.step1.outputs.tag }}
+      ref: ${{ steps.step1.outputs.ref }}
       version: ${{ steps.step1.outputs.version }}
 
     steps:
@@ -32,9 +24,9 @@ jobs:
         run: |
           git config --global fetch.parallel 0
           git config --global submodule.fetchJobs 0
-
+          
       - name: Git Clone
-        uses: actions/checkout@v6
+        uses: actions/checkout@v3
         with:
           ref: develop
           token: ${{ secrets.PAT_ALL_REPO }}
@@ -49,93 +41,101 @@ jobs:
           echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
           echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
           echo "version=2.8.$(curl -s -L 'https://api.carbonmod.gg/version?id=profiler&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
-          git config --global --add safe.directory "*"
+          git config --global --add safe.directory /__w/Carbon/Carbon
 
-      - name: Install MinGW (Windows Build Only)
-        if: matrix.group == 'Windows'
+      - name: Rust Setup
+        shell: bash
         run: |
-          sudo apt-get update
-          sudo apt-get install -y mingw-w64
+          apt update
+          apt install -y mingw-w64
 
-      - name: Cache Rust
-        uses: Swatinem/rust-cache@v2
-        with:
-          workspaces: Carbon.Core/Carbon.Native
+          rustup install stable
+          rustup default stable
+          rustup target add x86_64-pc-windows-gnu
+          rustup component add rust-std --target x86_64-pc-windows-gnu
+          rustup show
+          rustc --print sysroot
 
-      - name: Setup .NET 10 SDK
-        uses: actions/setup-dotnet@v5
+          which x86_64-w64-mingw32-dlltool || echo "dlltool not found"
+          x86_64-w64-mingw32-dlltool --version
+
+      - name: Setup .NET 8 SDK
+        uses: actions/setup-dotnet@v2
         with:
-          dotnet-version: |
-            10.0.x
+          dotnet-version: 8.0.406
+      
+      - name: Setup .NET 9 SDK
+        uses: actions/setup-dotnet@v2
+        with:
+          dotnet-version: 9.0.203
 
       - name: Carbon.Native Toolchain
         uses: dtolnay/rust-toolchain@stable
+
+      - name: Carbon.Native Build (Linux)
+        uses: ClementTsang/cargo-action@v0.0.3
         with:
-          targets: ${{ matrix.target }}
+          command: build
+          args: -r --target x86_64-unknown-linux-gnu
+          directory: Carbon.Core/Carbon.Native
 
-      - name: Build Native
-        working-directory: Carbon.Core/Carbon.Native
-        shell: bash
-        run: |
-          cargo build -r --target ${{ matrix.target }}
+      - name: Carbon.Native Build (Windows)
+        uses: ClementTsang/cargo-action@v0.0.3
+        with:
+          command: build
+          args: -r --target x86_64-pc-windows-gnu
+          directory: Carbon.Core/Carbon.Native
 
-      - name: Carbon Bootstrap CS
+      - name: Carbon Bootstrap
         shell: bash
         run: |
           dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/bootstrap.cs
-
-      - name: Carbon Update CS
-        shell: bash
-        run: |
           dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/update.cs
 
       - name: Profiler Build
         shell: bash
-        env:
-          VERSION: ${{ steps.step1.outputs.version }}
         run: |
-          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/profiler.cs Debug${{ matrix.build_arg }} HARMONYMOD profiler_build
+          export VERSION=${{ steps.step1.outputs.version }}
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/profiler.cs Debug HARMONYMOD profiler_build
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/profiler.cs DebugUnix HARMONYMOD profiler_build
 
       - name: Artifacts
-        uses: actions/upload-artifact@v5
+        uses: actions/upload-artifact@v4
         with:
-          name: build-${{ matrix.group }}
+          name: build
           path: |
             Release/Carbon.Linux.Profiler.tar.gz
             Release/Carbon.Windows.Profiler.zip
 
   release-on-commit:
     name: Profiler Release
-    needs: [ "build" ]
+    needs: ["build"]
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    steps:
-      - name: Git Clone
-        uses: actions/checkout@v6
 
+    steps:
       - name: 🗑️ Delete existing release tag
+        uses: dev-drprasad/delete-tag-and-release@92d94d77429cb0436597047a92369526a5824f50
+        with:
+          delete_release: true
+          tag_name: profiler_build
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release delete profiler_build --cleanup-tag --yes || echo "Release/Tag not found, nothing to delete"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: 💤 Sleep for 5 seconds
         run: sleep 5s
         shell: bash
 
       - name: ⬇️ Download artifacts
-        uses: actions/download-artifact@v6
+        uses: actions/download-artifact@v4
         with:
           path: Release
-          merge-multiple: true
 
-      - name: Display structure
+      - name: Display structure of downloaded files
         run: ls -R
         working-directory: Release
 
-      - name: 🏷️ Create Release
-        uses: softprops/action-gh-release@v2
+      - name: 🏷️ Update release tag
+        uses: softprops/action-gh-release@a92196038060e0c673cf3ba5b98710dd716731df
         with:
           draft: false
           prerelease: true
@@ -150,5 +150,5 @@ jobs:
             2. Unzip the archive to the HarmonyMods directory of your Rust Dedicated Server.
             3. Start the server and enjoy, or run `harmony.load Carbon.Profiler`.
           files: |
-            Release/Carbon.Windows.Profiler.zip
-            Release/Carbon.Linux.Profiler.tar.gz
+            Release/build/Carbon.Windows.Profiler.zip     
+            Release/build/Carbon.Linux.Profiler.tar.gz
